name: Publish Docker image

on:
  push:
    tags:
      - '*'

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish-docker-images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: Checkout and pull branch
        run: |
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          git checkout $LATEST_TAG

      - name: Setup buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERNAME }}
          password: ${{ secrets.DOCKERTOKEN }}

      - name: Docker meta for core 
        id: meta_core 
        uses: docker/metadata-action@v3
        with:
          images: codelit/medialit 

      - name: Build and push API 
        id: docker_build_api
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./apps/api/Dockerfile
          push: true
          tags: ${{ steps.meta_core.outputs.tags }}

      - name: Image digest
        run: echo ${{ steps.docker_build_api.outputs.digest }}